// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06.06.2025, 23:57:03
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/OSPanel/home/crumbleCookies/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/OSPanel/home/crumbleCookies/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/OSPanel/home/crumbleCookies/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/OSPanel/home/crumbleCookies/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/OSPanel/home/crumbleCookies/plugins/**/*.{js,ts,mjs}","C:/OSPanel/home/crumbleCookies/composables/**/*.{js,ts,mjs}","C:/OSPanel/home/crumbleCookies/utils/**/*.{js,ts,mjs}","C:/OSPanel/home/crumbleCookies/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/OSPanel/home/crumbleCookies/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/OSPanel/home/crumbleCookies/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/OSPanel/home/crumbleCookies/app.config.{js,ts,mjs}"]}},
{"content":["./components/**/*.{js,vue,ts}","./layouts/**/*.vue","./pages/**/*.vue","./plugins/**/*.{js,ts}","./app.vue","./error.vue"]},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;